# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdc2f4d136e4ed943d7e99ee7ab39fe99e0609a8d48b9745043d3b22130f4cedd3cc2213d6c28d5eea0c4777023af60eb85797e04323cf41a6d761e9442b22b7

test:
  secret_key_base: d43065eb5a5a4686546f6a8daa9f37d7d46a24fb8230d8aac3f76faa9c47ebdd2868afa4499b52bcb91d24a86ef0e59d7c266406ae2d857a63bf147d853425a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
